export const EDIT_ARTICLE_SUCCESS = 'EDIT_ARTICLE_SUCCESS';
export const EDIT_ARTICLE_FAILURE = 'EDIT_ARTICLE_FAILURE';

export const SET_DEVICE_INFO = 'SET_DEVICE_INFO';

export const UPDATE_CONNECTION_STATUS = 'UPDATE_CONNETION_STATUS';
